### PR TITLE
update link for options in README.md

### PR DESCRIPTION
**Pull request by gnyani**

### CODE REVIEW

**Comment by gnyani** [comment]
@jonschlinkert  can you please take a quick look.

**Comment by gnyani** [comment]
@jonschlinkert  Friendly Ping !!

**Comment by gnyani** [comment]
Ping

**Comment by gnyani** [comment]
Ping again !!

**Comment by tunnckoCore** [comment]
No matter how many times you ping, they probably won't come to your PR, because there is ton of stuff and more important than such typos in Open Source to do. Not offending you, just true, we are busy and rarely can get to such PRs :)

Thanks for your patience. ;)

**Review by tunnckoCore — CHANGES_REQUESTED** [review]
@gnyani change it in `.verb.md`. All mine, @jonschlinkert and @doowb READMEs for many many years are generated by [Verb (dev, the dev branch)](https://github.com/verbose/verb/tree/dev) and [verb-generate-readme](https://github.com/verbose/verb-generate-readme) using `.verb.md` as template file.

**Comment by gnyani** [comment]
No problem will close for now.

**Pull request closed without merging**
